using System.Security.Cryptography;
using System.Text;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MonitoringETL.Api.Data;
using MonitoringETL.Api.Models;
namespace MonitoringETL.Api.Controllers;

public sealed record LoginRequest(string Email,string MotDePasse,bool SeSouvenir=false);
public sealed record ForgotPasswordRequest(string Email);
public sealed record ResetPasswordRequest(string Email,string Token,string NouveauMotDePasse);
public sealed record ActivateInvitationRequest(string Email,string Token,string NouveauMotDePasse);
public sealed record ChangePasswordRequest(string AncienMotDePasse,string NouveauMotDePasse);

[ApiController,Route("api/auth")]
public sealed class AuthController(UserManager<ApplicationUser> users,SignInManager<ApplicationUser> signIn,MonitoringDbContext db,IWebHostEnvironment environment):ControllerBase{
 [AllowAnonymous,HttpPost("connexion")]
 public async Task<IActionResult> Login(LoginRequest request,CancellationToken ct){var user=await users.FindByEmailAsync(request.Email.Trim());if(user is null||!user.Actif)return Unauthorized(new{message="Identifiants incorrects."});var result=await signIn.CheckPasswordSignInAsync(user,request.MotDePasse,lockoutOnFailure:true);if(!result.Succeeded)return Unauthorized(new{message=result.IsLockedOut?"Compte temporairement verrouillé.":"Identifiants incorrects."});var now=DateTimeOffset.UtcNow;await signIn.SignInAsync(user,new AuthenticationProperties{IsPersistent=request.SeSouvenir,AllowRefresh=true,IssuedUtc=now,ExpiresUtc=now.Add(request.SeSouvenir?TimeSpan.FromDays(30):TimeSpan.FromHours(8))});user.DerniereConnexion=DateTime.UtcNow;db.JournauxAudit.Add(new JournalAudit{IdUtilisateur=user.Id,Action="CONNEXION",AdresseIP=HttpContext.Connection.RemoteIpAddress?.ToString(),Details=request.SeSouvenir?"Connexion persistante activée pour 30 jours.":"Connexion réussie pour la session courante."});await db.SaveChangesAsync(ct);return Ok(await UserInfo(user));}
 [Authorize,HttpPost("deconnexion")]public async Task<IActionResult> Logout(CancellationToken ct){var user=await users.GetUserAsync(User);if(user is not null){db.JournauxAudit.Add(new JournalAudit{IdUtilisateur=user.Id,Action="DECONNEXION",AdresseIP=HttpContext.Connection.RemoteIpAddress?.ToString(),Details="Déconnexion utilisateur."});await db.SaveChangesAsync(ct);}await signIn.SignOutAsync();return NoContent();}
 [Authorize,HttpGet("moi")]public async Task<IActionResult> Me(){var user=await users.GetUserAsync(User);return user is null?Unauthorized():Ok(await UserInfo(user));}
 [Authorize,HttpPost("changer-mot-de-passe")]
 public async Task<IActionResult> ChangePassword(ChangePasswordRequest request,CancellationToken ct){var user=await users.GetUserAsync(User);if(user is null)return Unauthorized();if(string.IsNullOrWhiteSpace(request.AncienMotDePasse)||string.IsNullOrWhiteSpace(request.NouveauMotDePasse))return BadRequest(new{message="Les deux mots de passe sont obligatoires."});var result=await users.ChangePasswordAsync(user,request.AncienMotDePasse,request.NouveauMotDePasse);if(!result.Succeeded)return ValidationProblem(new ValidationProblemDetails(result.Errors.GroupBy(x=>x.Code).ToDictionary(x=>x.Key,x=>x.Select(e=>e.Description).ToArray())));db.JournauxAudit.Add(new JournalAudit{IdUtilisateur=user.Id,Action="MODIFICATION_MOT_DE_PASSE",AdresseIP=HttpContext.Connection.RemoteIpAddress?.ToString(),Details="Mot de passe modifié."});await db.SaveChangesAsync(ct);return Ok(new{message="Mot de passe modifié."});}
 [AllowAnonymous,HttpPost("mot-de-passe-oublie")]public async Task<IActionResult> Forgot(ForgotPasswordRequest request){var user=await users.FindByEmailAsync(request.Email.Trim());if(user is null||!user.Actif)return Ok(new{message="Si le compte existe, une procédure de réinitialisation a été créée.",token=(string?)null});var token=await users.GeneratePasswordResetTokenAsync(user);return Ok(environment.IsDevelopment()?new{message="Jeton de développement généré.",token=(string?)token}:new{message="Si le compte existe, une procédure de réinitialisation a été créée.",token=(string?)null});}
 [AllowAnonymous,HttpPost("reinitialiser-mot-de-passe")]public async Task<IActionResult> Reset(ResetPasswordRequest request,CancellationToken ct){var user=await users.FindByEmailAsync(request.Email.Trim());if(user is null||!user.Actif)return BadRequest(new{message="Demande invalide."});var result=await users.ResetPasswordAsync(user,request.Token,request.NouveauMotDePasse);if(!result.Succeeded)return ValidationProblem(new ValidationProblemDetails(result.Errors.GroupBy(x=>x.Code).ToDictionary(x=>x.Key,x=>x.Select(e=>e.Description).ToArray())));db.JournauxAudit.Add(new JournalAudit{IdUtilisateur=user.Id,Action="REINITIALISATION_MOT_DE_PASSE",AdresseIP=HttpContext.Connection.RemoteIpAddress?.ToString(),Details="Mot de passe réinitialisé."});await db.SaveChangesAsync(ct);return Ok(new{message="Mot de passe réinitialisé."});}
 [AllowAnonymous,HttpPost("activer-invitation")]
 public async Task<IActionResult> ActivateInvitation(ActivateInvitationRequest request,CancellationToken ct){if(string.IsNullOrWhiteSpace(request.Email)||string.IsNullOrWhiteSpace(request.Token)||string.IsNullOrWhiteSpace(request.NouveauMotDePasse))return BadRequest(new{message="Demande d’activation invalide."});if(request.Token.Trim().Length>10||!request.Token.Trim().All(char.IsDigit))return BadRequest(new{message="Le code d’invitation doit contenir uniquement des chiffres (10 maximum)."});var user=await users.FindByEmailAsync(request.Email.Trim());if(user is null)return BadRequest(new{message="Demande d’activation invalide."});var now=DateTime.UtcNow;var tokenHash=Convert.ToBase64String(SHA256.HashData(Encoding.UTF8.GetBytes(request.Token.Trim())));var invitation=await db.Invitations.SingleOrDefaultAsync(x=>x.IdUtilisateur==user.Id&&x.TokenHash==tokenHash&&x.DateUtilisation==null&&x.DateExpiration>now,ct);if(invitation is null)return BadRequest(new{message="Invitation invalide ou expirée."});var removed=await users.RemovePasswordAsync(user);if(!removed.Succeeded)return ValidationProblem(new ValidationProblemDetails(removed.Errors.GroupBy(x=>x.Code).ToDictionary(x=>x.Key,x=>x.Select(e=>e.Description).ToArray())));var result=await users.AddPasswordAsync(user,request.NouveauMotDePasse);if(!result.Succeeded)return ValidationProblem(new ValidationProblemDetails(result.Errors.GroupBy(x=>x.Code).ToDictionary(x=>x.Key,x=>x.Select(e=>e.Description).ToArray())));user.Actif=true;invitation.DateUtilisation=now;var updated=await users.UpdateAsync(user);if(!updated.Succeeded)return ValidationProblem(new ValidationProblemDetails(updated.Errors.GroupBy(x=>x.Code).ToDictionary(x=>x.Key,x=>x.Select(e=>e.Description).ToArray())));db.JournauxAudit.Add(new JournalAudit{IdUtilisateur=user.Id,Action="ACTIVATION_INVITATION",AdresseIP=HttpContext.Connection.RemoteIpAddress?.ToString(),Details="Compte activé après acceptation de l’invitation."});await db.SaveChangesAsync(ct);return Ok(new{message="Compte activé. Vous pouvez maintenant vous connecter."});}
 private async Task<object> UserInfo(ApplicationUser user)=>new{user.Id,user.NomComplet,user.Email,user.PhotoProfil,user.Actif,roles=await users.GetRolesAsync(user)};
}
