using System.Security.Claims;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;

namespace MonitoringETL.Api.Controllers;

public sealed record ConfigurerValidationRequest(string BaseDonnees, string Schema, string Journal);

[Authorize(Roles = "ADMINISTRATEUR,ANALYSTE"), ApiController, Route("api/validation")]
public sealed class ValidationController(IConfiguration config) : ControllerBase
{
    private static readonly string[] Tables = Array.Empty<string>();
    private static readonly Regex Identifier = new("^[A-Za-z_][A-Za-z0-9_]*$", RegexOptions.Compiled);
    private string ConnectionString => config.GetConnectionString("ValidationDatabase") ?? config.GetConnectionString("MonitoringDatabase") ?? throw new InvalidOperationException("La connexion ValidationDatabase est absente.");
    private SqlConnection Open(string? database = null) { var b = new SqlConnectionStringBuilder(ConnectionString); if (!string.IsNullOrWhiteSpace(database)) b.InitialCatalog = database; return new SqlConnection(b.ConnectionString); }
    private static string Quote(string value) => $"[{value.Replace("]", "]]", StringComparison.Ordinal)}]";
    private static string TableName(string schema, string table) => $"{Quote(schema)}.{Quote(table)}";
    private static bool Valid(string value) => !string.IsNullOrWhiteSpace(value) && Identifier.IsMatch(value);
    private static string JournalName(string value) { var p = value.Split('.', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries); return p.Length == 2 && p.All(Valid) ? TableName(p[0], p[1]) : throw new InvalidOperationException("Journal de validation invalide."); }
    private async Task EnsureConfig(CancellationToken ct) { await using var c = Open(); await c.OpenAsync(ct); await using var q = new SqlCommand("IF OBJECT_ID('dbo.ValidationConfiguration','U') IS NULL CREATE TABLE dbo.ValidationConfiguration(Id int NOT NULL PRIMARY KEY CHECK(Id=1),BaseDonnees nvarchar(150) NOT NULL,SchemaTables nvarchar(128) NOT NULL,JournalTable nvarchar(200) NOT NULL,DateModification datetime2 NOT NULL DEFAULT sysutcdatetime())", c); await q.ExecuteNonQueryAsync(ct); }
    private async Task<(string Database,string Schema,string Journal)?> GetConfig(CancellationToken ct) { await EnsureConfig(ct); await using var c=Open(); await c.OpenAsync(ct); await using var q=new SqlCommand("SELECT BaseDonnees,SchemaTables,JournalTable FROM dbo.ValidationConfiguration WHERE Id=1",c); await using var r=await q.ExecuteReaderAsync(ct); return await r.ReadAsync(ct)?(r.GetString(0),r.GetString(1),r.GetString(2)):null; }
    private async Task<List<string>> GetIndicators(SqlConnection c,string schema,string table,CancellationToken ct){await using var q=new SqlCommand("SELECT c.name FROM sys.columns c JOIN sys.tables t ON t.object_id=c.object_id JOIN sys.schemas s ON s.schema_id=t.schema_id JOIN sys.types y ON y.user_type_id=c.user_type_id WHERE s.name=@s AND t.name=@t AND c.name NOT IN('Id','DateReference','DateChargement') AND y.name IN('tinyint','smallint','int','bigint','decimal','numeric','float','real','money','smallmoney') ORDER BY c.column_id",c);q.Parameters.AddWithValue("@s",schema);q.Parameters.AddWithValue("@t",table);var x=new List<string>();await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))x.Add(r.GetString(0));return x;}
    private async Task<(string Key,string? Date,string? Label)?> GetMapping(SqlConnection c,string schema,string table,CancellationToken ct){await using var q=new SqlCommand("SELECT KeyColumn,DateColumn,LabelColumn FROM dbo.ValidationTableMappings WHERE SchemaName=@s AND TableName=@t AND Actif=1",c);q.Parameters.AddWithValue("@s",schema);q.Parameters.AddWithValue("@t",table);await using var r=await q.ExecuteReaderAsync(ct);return await r.ReadAsync()?(r.GetString(0),r.IsDBNull(1)?null:r.GetString(1),r.IsDBNull(2)?null:r.GetString(2)):null;}
    private async Task<(string Database,string Schema,string Journal)> RequireConfig(CancellationToken ct) => await GetConfig(ct) ?? throw new InvalidOperationException("La validation des données n’est pas encore configurée par un administrateur.");

    [HttpGet("tables")]
    public async Task<IActionResult> List(CancellationToken ct) { var s=await GetConfig(ct); if(s is null)return Ok(Array.Empty<object>()); await using var c=Open(s.Value.Database); await c.OpenAsync(ct); await using var q=new SqlCommand("SELECT TableName FROM dbo.ValidationTableMappings WHERE SchemaName=@schema AND Actif=1 ORDER BY TableName",c);q.Parameters.AddWithValue("@schema",s.Value.Schema);var items=new List<object>();await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))items.Add(new{code=r.GetString(0),nom=r.GetString(0)});return Ok(items); }

    [HttpGet("statut")]
    public async Task<IActionResult> Status(CancellationToken ct) => Ok(new { configured = await GetConfig(ct) is not null });

    [Authorize(Roles="ADMINISTRATEUR"), HttpGet("configuration")]
    public async Task<IActionResult> Configuration(CancellationToken ct) { var s=await GetConfig(ct);if(s is null)return Ok(new{configured=false});await using var c=Open(s.Value.Database);await c.OpenAsync(ct);await using var q=new SqlCommand("SELECT COUNT(*) FROM dbo.ValidationTableMappings WHERE SchemaName=@schema AND Actif=1",c);q.Parameters.AddWithValue("@schema",s.Value.Schema);var tablesDeFaits=Convert.ToInt32(await q.ExecuteScalarAsync(ct));var b=new SqlConnectionStringBuilder(ConnectionString);return Ok(new{configured=true,serveur=b.DataSource,baseDonnees=s.Value.Database,schema=s.Value.Schema,tablesDeFaits,journal=s.Value.Journal}); }

    [Authorize(Roles="ADMINISTRATEUR"),HttpPost("configuration")]
    public async Task<IActionResult> Configure(ConfigurerValidationRequest request,CancellationToken ct) { var p=request.Journal.Split('.',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries);if(!Valid(request.Schema)||p.Length!=2||!p.All(Valid))return BadRequest(new{message="Schéma ou journal invalide."});await using var c=Open(request.BaseDonnees);await c.OpenAsync(ct);await using var q=new SqlCommand("SELECT COUNT(*) FROM sys.tables t JOIN sys.schemas s ON s.schema_id=t.schema_id WHERE s.name=@schema",c);q.Parameters.AddWithValue("@schema",request.Schema);if(Convert.ToInt32(await q.ExecuteScalarAsync(ct))==0)return BadRequest(new{message="Le schéma sélectionné ne contient aucune table de faits."});await EnsureConfig(ct);await using var cc=Open();await cc.OpenAsync(ct);await using var save=new SqlCommand("MERGE dbo.ValidationConfiguration AS t USING (SELECT 1 AS Id) AS s ON t.Id=s.Id WHEN MATCHED THEN UPDATE SET BaseDonnees=@db,SchemaTables=@schema,JournalTable=@journal,DateModification=sysutcdatetime() WHEN NOT MATCHED THEN INSERT(Id,BaseDonnees,SchemaTables,JournalTable) VALUES(1,@db,@schema,@journal);",cc);save.Parameters.AddWithValue("@db",request.BaseDonnees);save.Parameters.AddWithValue("@schema",request.Schema);save.Parameters.AddWithValue("@journal",request.Journal);await save.ExecuteNonQueryAsync(ct);return Ok(new{message="Configuration de validation enregistrée. Vous pouvez la modifier à tout moment."}); }

    [HttpGet("{table}")]
    public async Task<IActionResult> Rows(string table,CancellationToken ct) { if(!Valid(table))return BadRequest(new{message="Table de validation invalide."});var s=await RequireConfig(ct);await using var c=Open(s.Database);await c.OpenAsync(ct);var map=await GetMapping(c,s.Schema,table,ct);if(map is null)return BadRequest(new{message="Cette table n’est pas mappée."});var indicators=await GetIndicators(c,s.Schema,table,ct);if(!indicators.Any())return BadRequest(new{message="Aucun indicateur numérique trouvé."});var fields=string.Join(',',new[]{Quote(map.Value.Key),map.Value.Date is null?"NULL":Quote(map.Value.Date),map.Value.Label is null?"NULL":Quote(map.Value.Label)}.Concat(indicators.Select(Quote)));await using var q=new SqlCommand($"SELECT TOP 100 {fields} FROM {TableName(s.Schema,table)} ORDER BY {Quote(map.Value.Date??map.Value.Key)} DESC",c);var rows=new List<object>();await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct)){var values=new Dictionary<string,decimal>();for(var i=0;i<indicators.Count;i++)values[indicators[i]]=r.GetDecimal(i+3);rows.Add(new{id=Convert.ToInt64(r.GetValue(0)),dateReference=r.IsDBNull(1)?(DateTime?)null:r.GetDateTime(1),agence=r.IsDBNull(2)?null:r.GetString(2),valeurs=values});}return Ok(new{indicateurs=indicators,lignes=rows}); }
    public record Change(long Id,string Indicateur,decimal ValeurAjoutee,string Motif);
    [HttpPost("{table}/corrections")]
    public async Task<IActionResult> ChangeValue(string table,Change change,CancellationToken ct) { if(!Valid(table)||!Valid(change.Indicateur)||string.IsNullOrWhiteSpace(change.Motif))return BadRequest(new{message="Table, indicateur ou motif invalide."});var s=await RequireConfig(ct);await using var c=Open(s.Database);await c.OpenAsync(ct);var map=await GetMapping(c,s.Schema,table,ct);if(map is null||string.IsNullOrWhiteSpace(map.Value.Date))return BadRequest(new{message="Le mapping de clé ou de date est incomplet."});if(!(await GetIndicators(c,s.Schema,table,ct)).Contains(change.Indicateur,StringComparer.OrdinalIgnoreCase))return BadRequest(new{message="Indicateur numérique introuvable."});await using var tx=await c.BeginTransactionAsync(ct);decimal old;DateTime date;await using(var q=new SqlCommand($"SELECT {Quote(map.Value.Date)},{Quote(change.Indicateur)} FROM {TableName(s.Schema,table)} WHERE {Quote(map.Value.Key)}=@id",c,(SqlTransaction)tx)){q.Parameters.AddWithValue("@id",change.Id);await using var r=await q.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))return NotFound();date=r.GetDateTime(0);old=r.GetDecimal(1);}var next=old+change.ValeurAjoutee;await using(var q=new SqlCommand($"UPDATE {TableName(s.Schema,table)} SET {Quote(change.Indicateur)}=@next WHERE {Quote(map.Value.Key)}=@id; INSERT {JournalName(s.Journal)}(TableFait,DateReference,Indicateur,AncienneValeur,ValeurAjoutee,NouvelleValeur,Motif,Utilisateur) VALUES(@table,@date,@indicator,@old,@addition,@next,@reason,@user)",c,(SqlTransaction)tx)){q.Parameters.AddWithValue("@next",next);q.Parameters.AddWithValue("@id",change.Id);q.Parameters.AddWithValue("@table",table);q.Parameters.AddWithValue("@date",date);q.Parameters.AddWithValue("@indicator",change.Indicateur);q.Parameters.AddWithValue("@old",old);q.Parameters.AddWithValue("@addition",change.ValeurAjoutee);q.Parameters.AddWithValue("@reason",change.Motif);q.Parameters.AddWithValue("@user",User.FindFirstValue(ClaimTypes.Email)??User.Identity?.Name??"Utilisateur");await q.ExecuteNonQueryAsync(ct);}await tx.CommitAsync(ct);return Ok(new{message="Correction appliquée et audit enregistrés.",ancienneValeur=old,nouvelleValeur=next}); }
    [Authorize(Roles="ADMINISTRATEUR,ANALYSTE"),HttpPost("{table}/corrections-v2")]
    public async Task<IActionResult> ChangeValueV2(string table,Change change,CancellationToken ct){var s=await RequireConfig(ct);if(!Valid(table)||!Valid(change.Indicateur)||string.IsNullOrWhiteSpace(change.Motif))return BadRequest();await using var c=Open(s.Database);await c.OpenAsync(ct);var m=await GetMapping(c,s.Schema,table,ct);if(m is null||m.Value.Date is null||!(await GetIndicators(c,s.Schema,table,ct)).Contains(change.Indicateur,StringComparer.OrdinalIgnoreCase))return BadRequest();await using var tx=await c.BeginTransactionAsync(ct);decimal old;DateTime date;await using(var q=new SqlCommand($"SELECT {Quote(m.Value.Date)},{Quote(change.Indicateur)} FROM {TableName(s.Schema,table)} WHERE {Quote(m.Value.Key)}=@id",c,(SqlTransaction)tx)){q.Parameters.AddWithValue("@id",change.Id);await using var r=await q.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))return NotFound();date=r.GetDateTime(0);old=r.GetDecimal(1);}var next=old+change.ValeurAjoutee;await using(var q=new SqlCommand($"UPDATE {TableName(s.Schema,table)} SET {Quote(change.Indicateur)}=@next WHERE {Quote(m.Value.Key)}=@id;INSERT {JournalName(s.Journal)}(TableFait,IdLigne,DateReference,Indicateur,AncienneValeur,ValeurAjoutee,NouvelleValeur,Motif,Utilisateur) VALUES(@t,@id,@d,@i,@o,@a,@n,@r,@u)",c,(SqlTransaction)tx)){q.Parameters.AddWithValue("@id",change.Id);q.Parameters.AddWithValue("@next",next);q.Parameters.AddWithValue("@t",table);q.Parameters.AddWithValue("@d",date);q.Parameters.AddWithValue("@i",change.Indicateur);q.Parameters.AddWithValue("@o",old);q.Parameters.AddWithValue("@a",change.ValeurAjoutee);q.Parameters.AddWithValue("@n",next);q.Parameters.AddWithValue("@r",change.Motif);q.Parameters.AddWithValue("@u",User.FindFirstValue(ClaimTypes.Email)??"Utilisateur");await q.ExecuteNonQueryAsync(ct);}await tx.CommitAsync(ct);return Ok(new{ancienneValeur=old,nouvelleValeur=next});}

    [Authorize(Roles="ADMINISTRATEUR,ANALYSTE"),HttpPost("journal/{id:long}/annuler")]
    public async Task<IActionResult> Undo(long id,CancellationToken ct){var s=await RequireConfig(ct);await using var c=Open(s.Database);await c.OpenAsync(ct);await using var q=new SqlCommand($"SELECT TableFait,IdLigne,Indicateur,AncienneValeur,Statut FROM {JournalName(s.Journal)} WHERE Id=@id",c);q.Parameters.AddWithValue("@id",id);await using var r=await q.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))return NotFound();var table=r.GetString(0);if(r.IsDBNull(1))return BadRequest(new{message="Cette ancienne correction ne peut pas être annulée automatiquement."});var line=r.GetInt64(1);var indicator=r.GetString(2);var previous=r.GetDecimal(3);var status=r.GetString(4);await r.CloseAsync();if(status=="ANNULE")return Conflict(new{message="Cette correction est déjà annulée."});var m=await GetMapping(c,s.Schema,table,ct);if(m is null)return BadRequest();await using var tx=await c.BeginTransactionAsync(ct);await using(var u=new SqlCommand($"UPDATE {TableName(s.Schema,table)} SET {Quote(indicator)}=@v WHERE {Quote(m.Value.Key)}=@id; UPDATE {JournalName(s.Journal)} SET Statut='ANNULE' WHERE Id=@j",c,(SqlTransaction)tx)){u.Parameters.AddWithValue("@v",previous);u.Parameters.AddWithValue("@id",line);u.Parameters.AddWithValue("@j",id);await u.ExecuteNonQueryAsync(ct);}await tx.CommitAsync(ct);return Ok(new{message="Correction annulée.",nouvelleValeur=previous});}

    [HttpGet("journal")]
    public async Task<IActionResult> Log(CancellationToken ct) { var s=await GetConfig(ct);if(s is null)return Ok(Array.Empty<object>());await using var c=Open(s.Value.Database);await c.OpenAsync(ct);await using var q=new SqlCommand($"SELECT TOP 200 Id,TableFait,DateReference,Indicateur,AncienneValeur,ValeurAjoutee,NouvelleValeur,Motif,Utilisateur,DateHeure,Statut FROM {JournalName(s.Value.Journal)} ORDER BY Id DESC",c);var rows=new List<object>();await using var r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))rows.Add(new{id=r.GetInt64(0),tableFait=r.GetString(1),dateReference=r.GetDateTime(2),indicateur=r.GetString(3),ancienneValeur=r.GetDecimal(4),valeurAjoutee=r.GetDecimal(5),nouvelleValeur=r.GetDecimal(6),motif=r.GetString(7),utilisateur=r.GetString(8),dateHeure=r.GetDateTime(9),statut=r.GetString(10)});return Ok(rows); }
}
