import {useState} from 'react';
import {ArrowRight,Eye,EyeOff,LockKeyhole,ShieldCheck,UserRound} from 'lucide-react';
import logo from '../assets/bcc-logo.png';
import {api} from '../api';

export default function AuthPage({mode='login',onAuthenticated,onInitialized}){
 const[showPassword,setShowPassword]=useState(false),[email,setEmail]=useState(''),[name,setName]=useState(''),[password,setPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[remember,setRemember]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(false),[forgotten,setForgotten]=useState(false),[info,setInfo]=useState('');
 async function submit(event){event.preventDefault();setError('');if(!email.trim()||!password){setError('Veuillez renseigner votre adresse email et votre mot de passe.');return}if(mode==='setup'&&password.length<8){setError('Le mot de passe doit contenir au moins 8 caractères.');return}if(mode==='setup'&&(!name.trim()||password!==confirmPassword)){setError(!name.trim()?'Le nom complet est obligatoire.':'Les mots de passe ne correspondent pas.');return}setLoading(true);try{if(mode==='setup'){await api.setup({nomComplet:name,email,motDePasse:password});onInitialized()}else{onAuthenticated(await api.login({email,motDePasse:password,seSouvenir:remember}))}}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function forgot(){if(!email.trim()){setError('Saisissez votre email avant de demander une réinitialisation.');return}setLoading(true);try{const result=await api.forgot(email);setInfo(result.token?`Mode test — jeton généré : ${result.token}`:result.message);setForgotten(true)}catch(e){setError(e.message)}finally{setLoading(false)}}
 return <main className="bcc-login-page" style={{'--bcc-logo':`url(${logo})`}}><div className="bcc-logo-pattern" aria-hidden="true">{Array.from({length:12},(_,i)=><img key={i} src={logo} alt=""/>)}</div><section className="bcc-login-shell"><div className="bcc-login-intro"><div className="bcc-login-official"><span><img src={logo} alt="Logo de la Banque Centrale du Congo"/></span><p>BANQUE CENTRALE<br/><strong>DU CONGO</strong></p></div><div className="bcc-intro-copy"><span className="bcc-platform-tag">PLATEFORME INTERNE</span><h1>Monitoring<br/><em>ETL</em></h1><p>Supervisez vos flux de données avec précision, fiabilité et sécurité.</p></div><div className="bcc-intro-security"><ShieldCheck/><span><b>Accès sécurisé</b><small>Vos données sont protégées</small></span></div></div>
 <form className="bcc-login-form" onSubmit={submit} noValidate><div className="bcc-mobile-brand"><img src={logo} alt="Logo BCC"/><b>BANQUE CENTRALE DU CONGO</b></div><header><span>{mode==='setup'?'Première ouverture':'Heureux de vous revoir'}</span><h2>{mode==='setup'?'Initialisation':'Connexion'}</h2><p>{mode==='setup'?'Créez le premier compte administrateur sécurisé.':'Accédez à votre espace de supervision.'}</p></header>
 {mode==='setup'&&<label className="bcc-field"><span>Nom complet</span><div><UserRound/><input autoFocus autoComplete="name" value={name} onChange={e=>setName(e.target.value)} placeholder="Votre nom complet"/></div></label>}
 <label className="bcc-field"><span>Adresse email</span><div><UserRound/><input autoFocus={mode==='login'} type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} placeholder="nom@bcc.cd"/></div></label>
 <label className="bcc-field"><span>Mot de passe</span><div><LockKeyhole/><input type={showPassword?'text':'password'} minLength={mode==='setup'?8:undefined} autoComplete={mode==='setup'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder={mode==='setup'?'8 caractères minimum':'Saisissez votre mot de passe'}/><button type="button" aria-label="Afficher ou masquer" onClick={()=>setShowPassword(v=>!v)}>{showPassword?<EyeOff/>:<Eye/>}</button></div></label>
 {mode==='setup'&&<label className="bcc-field"><span>Confirmer le mot de passe</span><div><LockKeyhole/><input type={showPassword?'text':'password'} autoComplete="new-password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} placeholder="Confirmez le mot de passe"/></div></label>}
 {mode==='login'&&<div className="bcc-login-options"><label><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/><span>Se souvenir de moi</span></label><button type="button" onClick={forgot}>Mot de passe oublié ?</button></div>}{error&&<p className="bcc-login-error" role="alert">{error}</p>}<button className="bcc-login-submit" disabled={loading}>{loading?'Veuillez patienter…':mode==='setup'?'Créer mon compte':'Se connecter'} {!loading&&<ArrowRight/>}</button><p className="bcc-login-help"><ShieldCheck/> Connexion sécurisée par ASP.NET Core Identity</p></form></section><footer className="bcc-login-footer">© 2026 Banque Centrale du Congo <i/> Direction des Systèmes d’Information</footer>
 {forgotten&&<div className="bcc-forgotten-backdrop" onClick={()=>setForgotten(false)}><section className="bcc-forgotten-card" role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()}><ShieldCheck/><h2>Réinitialisation du mot de passe</h2><p>{info}</p><button onClick={()=>setForgotten(false)}>Fermer</button></section></div>}</main>
}
