import { useEffect, useState } from 'react';
import { Bell, Building2, Check, Clock3, Database, Save, TrendingUp } from 'lucide-react';

const defaults={background:true,tips:true,system:false,organization:'Banque Centrale du Congo',acronym:'BCC',database:'DB_Monitoring_ETL',table:'tbl_suivi_etl'};
function Switch({value,onChange,label}){return <button type="button" className={`general-switch ${value?'on':''}`} role="switch" aria-checked={value} aria-label={label} onClick={()=>onChange(!value)}><i/></button>}
function Section({icon:Icon,title,children,className=''}){return <section className={`general-card ${className}`}><h3><span><Icon/></span>{title}</h3>{children}</section>}
function Field({label,children}){return <label className="general-field"><span>{label}</span>{children}</label>}
export default function GeneralSettings(){const[state,setState]=useState(()=>{try{return{...defaults,...JSON.parse(localStorage.getItem('bcc-general-settings'))}}catch{return defaults}}),[saved,setSaved]=useState(false);const set=(key,value)=>setState(s=>({...s,[key]:value}));const save=()=>{localStorage.setItem('bcc-general-settings',JSON.stringify(state));setSaved(true)};useEffect(()=>{if(saved){const t=setTimeout(()=>setSaved(false),2200);return()=>clearTimeout(t)}},[saved]);return <div className="general-settings"><h2>Paramètres de l’application</h2><div className="general-grid">
<Section icon={Building2} title="Informations de l’organisation"><Field label="Nom de l’organisation"><input value={state.organization} onChange={e=>set('organization',e.target.value)}/></Field><Field label="Sigle"><input value={state.acronym} onChange={e=>set('acronym',e.target.value)}/></Field><Field label="Fuseau horaire"><select><option>(UTC+01:00) Bruxelles, Kinshasa</option></select></Field><Field label="Langue par défaut"><select><option>Français</option><option>Anglais</option></select></Field></Section>
<Section icon={Database} title="Paramètres des données"><Field label="Base de données de suivi"><input value={state.database} onChange={e=>set('database',e.target.value)}/></Field><Field label="Table de suivi"><input value={state.table} onChange={e=>set('table',e.target.value)}/></Field><Field label="Connexion par défaut"><select><option>Lecture seule</option><option>Lecture et écriture</option></select></Field><Field label="Durée de conservation des historiques (jours)"><input type="number" defaultValue="365"/></Field></Section>
<Section icon={Clock3} title="Paramètres de rafraîchissement"><Field label="Actualisation automatique du tableau de bord"><select><option>Toutes les 5 minutes</option><option>Toutes les 15 minutes</option><option>Toutes les heures</option></select></Field><Field label="Actualisation des données en arrière-plan"><Switch value={state.background} onChange={v=>set('background',v)} label="Actualisation en arrière-plan"/></Field><Field label="Heure de rafraîchissement pour les rapports"><input type="time" defaultValue="00:00"/></Field><Field label="Format de la date"><select><option>JJ/MM/AAAA</option><option>MM/JJ/AAAA</option></select></Field><Field label="Format de l’heure"><select><option>24 heures (HH:mm:ss)</option><option>12 heures (hh:mm AM/PM)</option></select></Field></Section>
<Section icon={TrendingUp} title="Paramètres d’affichage"><Field label="Thème"><select><option>Clair</option><option>Sombre</option><option>Système</option></select></Field><Field label="Couleur principale"><span className="general-color"><i/>#0D47A1</span></Field><Field label="Densité des données dans les tableaux"><select><option>Normale</option><option>Compacte</option><option>Aérée</option></select></Field><Field label="Affichage des valeurs"><select><option>Avec séparateur de milliers</option><option>Valeurs brutes</option></select></Field></Section>
<Section icon={Bell} title="Autres préférences" className="general-preferences"><div><Field label="Afficher les conseils d’utilisation"><Switch value={state.tips} onChange={v=>set('tips',v)} label="Conseils d’utilisation"/></Field><Field label="Afficher les informations système"><Switch value={state.system} onChange={v=>set('system',v)} label="Informations système"/></Field></div><div><Field label="Nombre d’éléments par page"><select><option>10</option><option>20</option><option>50</option></select></Field><Field label="Page d’accueil par défaut après connexion"><select><option>Tableau de bord</option><option>Suivi des chargements</option></select></Field></div><footer><span className={saved?'visible':''}><Check/>Modifications enregistrées</span><button type="button" onClick={save}><Save/>Enregistrer les modifications</button></footer></Section>
</div></div>}
