import { useEffect, useState } from 'react';
import { Bell, Building2, Check, Clock3, Database, Save, TrendingUp } from 'lucide-react';
import { api } from '../api';
import CustomSelect from './CustomSelect';
import { applyGeneralPreferences, defaultGeneralPreferences } from '../preferences';
import { useActiveSource } from '../active-source';

const defaults = defaultGeneralPreferences;
const options = {
  timezone: [{ value: 'kinshasa', label: '(UTC+01:00) Bruxelles, Kinshasa' }], language: [{ value: 'fr', label: 'Français' }, { value: 'en', label: 'Anglais' }], connectionMode: [{ value: 'read', label: 'Lecture seule' }, { value: 'managed', label: 'Gérée par le backend' }], refreshInterval: [{ value: '5', label: 'Toutes les 5 minutes' }, { value: '15', label: 'Toutes les 15 minutes' }, { value: '30', label: 'Toutes les 30 minutes' }, { value: '0', label: 'Désactivée' }], dateFormat: [{ value: 'dmy', label: 'JJ/MM/AAAA' }, { value: 'ymd', label: 'AAAA-MM-JJ' }], theme: [{ value: 'light', label: 'Clair' }, { value: 'system', label: 'Selon le système' }], density: [{ value: 'compact', label: 'Compacte' }, { value: 'normal', label: 'Normale' }, { value: 'comfortable', label: 'Confortable' }], pageSize: [{ value: '10', label: '10 éléments' }, { value: '25', label: '25 éléments' }, { value: '50', label: '50 éléments' }], homePage: [{ value: 'dashboard', label: 'Tableau de bord' }, { value: 'history', label: 'Historique' }, { value: 'alerts', label: 'Alertes' }] };
function Switch({ value, onChange, label }) { return <button type="button" className={`general-switch ${value ? 'on' : ''}`} role="switch" aria-checked={value} aria-label={label} onClick={() => onChange(!value)}><i /></button>; }
function Section({ icon: Icon, title, children, className = '' }) { return <section className={`general-card ${className}`}><h3><span><Icon /></span>{title}</h3>{children}</section>; }
function Field({ label, children }) { return <div className="general-field"><span>{label}</span>{children}</div>; }
function Choice({ label, value, onChange, items }) { return <Field label={label}><CustomSelect value={value} onChange={onChange} options={items} ariaLabel={label} /></Field>; }

export default function GeneralSettings() {
  const { sourceId } = useActiveSource();
  useEffect(() => { document.documentElement.classList.toggle('monitoring-source-configured', Boolean(sourceId)); return () => document.documentElement.classList.remove('monitoring-source-configured'); }, [sourceId]);
  const [state, setState] = useState(defaults), [saved, setSaved] = useState(false), [error, setError] = useState(''), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false);
  const set = (key, value) => { setSaved(false); setState(current => ({ ...current, [key]: value })); };
  useEffect(() => { api.preferences().then(result => setState({ ...defaults, ...(result.general || {}) })).catch(exception => setError(exception.message)).finally(() => setLoading(false)); }, []);
  const save = async () => { setSaving(true); setError(''); try { await api.savePreferences({ general: state }); applyGeneralPreferences(state); setSaved(true); } catch (exception) { setError(exception.message); } finally { setSaving(false); } };
  if (loading) return <div className="tracking-empty">Chargement des préférences…</div>;
  return <div className="general-settings">{error && <p className="register-error">{error}</p>}<h2>Préférences de l’interface</h2><div className="general-grid">
    <Section icon={Building2} title="Informations de l’organisation"><Field label="Nom de l’organisation"><input value={state.organization} onChange={event => set('organization', event.target.value)} /></Field><Field label="Sigle"><input value={state.acronym} onChange={event => set('acronym', event.target.value)} /></Field><Choice label="Fuseau horaire" value={state.timezone} onChange={value => set('timezone', value)} items={options.timezone} /><Choice label="Langue par défaut" value={state.language} onChange={value => set('language', value)} items={options.language} /></Section>
    <Section icon={Database} title="Données surveillées"><Field label="Base de données de suivi"><input value="MonitoringETL_BCC" readOnly /></Field><Field label="Table de suivi"><input value="dbo.SuiviChargement" readOnly /></Field><Choice label="Connexion par défaut" value={state.connectionMode} onChange={value => set('connectionMode', value)} items={options.connectionMode} /><Field label="Durée de conservation (jours)"><input type="number" min="30" max="3650" value={state.retentionDays} onChange={event => set('retentionDays', Number(event.target.value))} /></Field></Section>
    <Section icon={Clock3} title="Paramètres de rafraîchissement"><Choice label="Actualisation du tableau de bord" value={state.refreshInterval} onChange={value => set('refreshInterval', value)} items={options.refreshInterval} /><Field label="Actualisation en arrière-plan"><Switch value={state.background} onChange={value => set('background', value)} label="Actualisation en arrière-plan" /></Field><Field label="Heure de rafraîchissement des rapports"><input type="time" value={state.reportRefresh} onChange={event => set('reportRefresh', event.target.value)} /></Field><Choice label="Format de la date" value={state.dateFormat} onChange={value => set('dateFormat', value)} items={options.dateFormat} /></Section>
    <Section icon={TrendingUp} title="Paramètres d’affichage"><Choice label="Thème" value={state.theme} onChange={value => set('theme', value)} items={options.theme} /><Field label="Couleur principale"><span className="general-color"><i />Bleu BCC</span></Field><Choice label="Densité des tableaux" value={state.density} onChange={value => set('density', value)} items={options.density} /></Section>
    <Section icon={Bell} title="Autres préférences" className="general-preferences"><div><Field label="Afficher les conseils d’utilisation"><Switch value={state.tips} onChange={value => set('tips', value)} label="Conseils d’utilisation" /></Field><Field label="Afficher les informations système"><Switch value={state.system} onChange={value => set('system', value)} label="Informations système" /></Field></div><div><Choice label="Éléments par page" value={state.pageSize} onChange={value => set('pageSize', value)} items={options.pageSize} /><Choice label="Page d’accueil" value={state.homePage} onChange={value => set('homePage', value)} items={options.homePage} /></div><footer><span className={saved ? 'visible' : ''}><Check />Modifications enregistrées</span><button type="button" disabled={saving} onClick={save}><Save />{saving ? 'Enregistrement…' : 'Enregistrer les modifications'}</button></footer></Section>
  </div></div>;
}
