import { useEffect, useState } from 'react';
import { Bell, Check, Clock3, Mail, MessageSquareText, Save, Send, Settings, TestTube2, Users, Webhook } from 'lucide-react';
const defaults={enabled:true,email:true,sms:true,inApp:true,webhook:false,daily:true,weekly:true,events:[true,true,true,true,true,true,true,true,false]};
function Switch({checked,onChange,label}){return <button type="button" className={`notification-switch ${checked?'on':''}`} role="switch" aria-checked={checked} aria-label={label} onClick={()=>onChange(!checked)}><span/></button>}
function Title({icon:Icon,children}){return <h2 className="notification-card-title"><span><Icon/></span>{children}</h2>}
export default function NotificationSettings(){
 const [settings,setSettings]=useState(()=>{try{return {...defaults,...JSON.parse(localStorage.getItem('bcc-notifications'))}}catch{return defaults}}),[saved,setSaved]=useState(false),set=(key,value)=>setSettings(c=>({...c,[key]:value}));
 const toggleEvent=index=>setSettings(c=>({...c,events:c.events.map((value,i)=>i===index?!value:value)})),save=()=>{localStorage.setItem('bcc-notifications',JSON.stringify(settings));setSaved(true)};
 useEffect(()=>{if(!saved)return;const timer=setTimeout(()=>setSaved(false),2200);return()=>clearTimeout(timer)},[saved]);
 const events=[['Échecs de chargement (Staging ou DW)',"Notifier en cas d’échec d’un chargement."],['Alertes importantes','Notifier les alertes importantes.'],['Maintenances planifiées','Notifier les maintenances et interruptions planifiées.'],['Chargements réussis','Notifier lorsqu’un chargement est réussi.'],['Chargements non exécutés',"Notifier lorsqu’un chargement n’a pas été exécuté."],['Modifications système','Notifier les changements de configuration ou système.'],['Alertes critiques','Notifier immédiatement les alertes critiques.'],['Performances','Notifier en cas de dépassement des seuils de performance.'],['Tests et simulations','Notifier les événements de test uniquement.']];
 return <div className="notification-settings">
  <section className="notification-card"><Title icon={Settings}>Paramètres généraux des notifications</Title><div className="notification-row"><div><b>Activer les notifications</b><p>Recevoir des notifications sur les événements du processus ETL.</p></div><Switch checked={settings.enabled} onChange={v=>set('enabled',v)} label="Activer les notifications"/></div><label className="notification-field"><b>Fuseau horaire</b><select defaultValue="kinshasa"><option value="kinshasa">(UTC+01:00) Bruxelles, Kinshasa</option><option>(UTC+00:00) Londres</option></select></label><div className="notification-field"><b>Heures d’envoi autorisées</b><div className="notification-time-range"><label><input type="time" defaultValue="07:00"/><Clock3/></label><i>–</i><label><input type="time" defaultValue="22:00"/><Clock3/></label></div><small>Les notifications ne seront envoyées qu’entre ces heures.</small></div></section>
  <section className="notification-card"><Title icon={Send}>Canaux de notification</Title>{[[Mail,'Email','Recevoir les notifications par email.','email'],[MessageSquareText,'SMS','Recevoir les notifications par SMS.','sms'],[Bell,'Notifications in-app',"Afficher les notifications dans l’application.",'inApp'],[Webhook,'Webhook','Envoyer les notifications vers un endpoint externe.','webhook']].map(([Icon,title,copy,key])=><div className="channel-row" key={key}><Icon/><div><b>{title}</b><p>{copy}</p></div><Switch checked={settings[key]} onChange={v=>set(key,v)} label={title}/></div>)}<div className="webhook-line"><label>URL du webhook</label><input placeholder="https://exemple.com/webhook/etl" disabled={!settings.webhook}/><button type="button" disabled={!settings.webhook} onClick={()=>alert('Test du webhook envoyé avec succès.')}><TestTube2/>Tester le webhook</button></div></section>
  <section className="notification-card"><Title icon={Clock3}>Fréquence des résumés</Title><div className="summary-row"><div><b>Rapport quotidien de synthèse</b><p>Recevoir un résumé quotidien des chargements ETL.</p></div><Switch checked={settings.daily} onChange={v=>set('daily',v)} label="Rapport quotidien"/><label><span>Heure d’envoi</span><span className="summary-time"><input type="time" defaultValue="08:00"/><Clock3/></span></label></div><div className="summary-row"><div><b>Rapport hebdomadaire</b><p>Recevoir un résumé hebdomadaire détaillé.</p></div><Switch checked={settings.weekly} onChange={v=>set('weekly',v)} label="Rapport hebdomadaire"/><label><span>Jour d’envoi</span><select><option>Lundi</option></select></label><label><span>Heure d’envoi</span><span className="summary-time"><input type="time" defaultValue="09:00"/><Clock3/></span></label></div></section>
  <section className="notification-card"><Title icon={Users}>Destinataires par défaut</Title><label className="recipient-row"><span><b>Administrateurs</b><small>Tous les administrateurs recevront les notifications critiques par défaut.</small></span><select><option>Tous les administrateurs</option></select></label><label className="recipient-row"><span><b>Équipe ETL</b><small>Notifications envoyées à l’équipe en charge des processus ETL.</small></span><select><option>Équipe ETL</option></select></label><label className="recipient-row"><span><b>Destinataires supplémentaires</b><small>Ajouter d’autres adresses email (séparées par des virgules).</small></span><input placeholder="exemple@bcc.cd, autre@bcc.cd"/></label></section>
  <section className="notification-card notification-events"><Title icon={Bell}>Types d’événements à notifier</Title><div className="events-grid">{events.map(([title,copy],index)=><label className="event-option" key={title}><input type="checkbox" checked={settings.events[index]} onChange={()=>toggleEvent(index)}/><span><b>{title}</b><small>{copy}</small></span></label>)}</div><div className="notification-save"><span className={saved?'visible':''}><Check/>Modifications enregistrées</span><button type="button" onClick={save}><Save/>Enregistrer les modifications</button></div></section>
 </div>
}
