import { useEffect, useState } from 'react';
import { Bell, Check, Clock3, Mail, MessageSquareText, Save, Send, Settings, Users, Webhook } from 'lucide-react';
import { api } from '../api';

const defaults = { enabled: true, email: true, sms: true, inApp: true, webhook: false, daily: true, weekly: true, timezone: 'kinshasa', events: [true, true, true, true, true, true, true, true, false] };
function Switch({ checked, onChange, label }) { return <button type="button" className={`notification-switch ${checked ? 'on' : ''}`} role="switch" aria-checked={checked} aria-label={label} onClick={() => onChange(!checked)}><span /></button>; }
function Title({ icon: Icon, children }) { return <h2 className="notification-card-title"><span><Icon /></span>{children}</h2>; }
export default function NotificationSettings() {
  const [settings, setSettings] = useState(defaults), [saved, setSaved] = useState(false), [error, setError] = useState(''), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false);
  const set = (key, value) => setSettings(current => ({ ...current, [key]: value }));
  useEffect(() => { api.preferences().then(result => setSettings({ ...defaults, ...(result.notifications || {}) })).catch(exception => setError(exception.message)).finally(() => setLoading(false)); }, []);
  const toggleEvent = index => set('events', settings.events.map((value, current) => current === index ? !value : value));
  const save = async () => { setSaving(true); setError(''); try { await api.savePreferences({ notifications: settings }); setSaved(true); } catch (exception) { setError(exception.message); } finally { setSaving(false); } };
  const events = [['Échecs de chargement (Staging ou DW)', 'Notifier en cas d’échec d’un chargement.'], ['Alertes importantes', 'Notifier les alertes importantes.'], ['Maintenances planifiées', 'Notifier les maintenances et interruptions planifiées.'], ['Chargements réussis', 'Notifier lorsqu’un chargement est réussi.'], ['Chargements non exécutés', 'Notifier lorsqu’un chargement n’a pas été exécuté.'], ['Modifications système', 'Notifier les changements de configuration ou système.'], ['Alertes critiques', 'Notifier immédiatement les alertes critiques.'], ['Performances', 'Notifier en cas de dépassement des seuils de performance.'], ['Tests et simulations', 'Notifier les événements de test uniquement.']];
  if (loading) return <div className="tracking-empty">Chargement des préférences de notification…</div>;
  return <div className="notification-settings">{error && <p className="register-error">{error}</p>}<section className="notification-card"><Title icon={Settings}>Paramètres généraux des notifications</Title><div className="notification-row"><div><b>Activer les notifications</b><p>Recevoir des notifications sur les événements du processus ETL.</p></div><Switch checked={settings.enabled} onChange={value => set('enabled', value)} label="Activer les notifications" /></div><label className="notification-field"><b>Fuseau horaire</b><select defaultValue="kinshasa"><option value="kinshasa">(UTC+01:00) Bruxelles, Kinshasa</option></select></label></section>
    <section className="notification-card"><Title icon={Send}>Canaux de notification</Title>{[[Mail, 'Email', 'email'], [MessageSquareText, 'SMS', 'sms'], [Bell, 'Notifications in-app', 'inApp'], [Webhook, 'Webhook', 'webhook']].map(([Icon, title, key]) => <div className="channel-row" key={key}><Icon /><div><b>{title}</b><p>Préférence de canal enregistrée avec votre compte.</p></div><Switch checked={settings[key]} onChange={value => set(key, value)} label={title} /></div>)}</section>
    <section className="notification-card"><Title icon={Clock3}>Fréquence des résumés</Title><div className="summary-row"><div><b>Rapport quotidien de synthèse</b><p>Recevoir un résumé quotidien des chargements ETL.</p></div><Switch checked={settings.daily} onChange={value => set('daily', value)} label="Rapport quotidien" /></div><div className="summary-row"><div><b>Rapport hebdomadaire</b><p>Recevoir un résumé hebdomadaire détaillé.</p></div><Switch checked={settings.weekly} onChange={value => set('weekly', value)} label="Rapport hebdomadaire" /></div></section>
    <section className="notification-card"><Title icon={Users}>Destinataires par défaut</Title><p>Les destinataires sont déterminés par les rôles administrés côté serveur.</p></section>
    <section className="notification-card notification-events"><Title icon={Bell}>Types d’événements à notifier</Title><div className="events-grid">{events.map(([title, copy], index) => <label className="event-option" key={title}><input type="checkbox" checked={settings.events[index]} onChange={() => toggleEvent(index)} /><span><b>{title}</b><small>{copy}</small></span></label>)}</div><div className="notification-save"><span className={saved ? 'visible' : ''}><Check />Modifications enregistrées</span><button type="button" disabled={saving} onClick={save}><Save />{saving ? 'Enregistrement…' : 'Enregistrer les modifications'}</button></div></section>
  </div>;
}
