import { useMemo, useState } from 'react';
import { ArrowRight, CalendarDays, Check, CheckCircle2, ChevronDown, ChevronsUpDown, Clock3, Database, FileText, Landmark, RefreshCw, Server } from 'lucide-react';
import bccLogo from '../assets/bcc-logo.png';
import '../source-selector.css';

// Données de démonstration uniquement. À remplacer plus tard par GET /api/sources.
const DEMO_SOURCES=[
 {id:'demo-monitoring-primary',name:'Base de suivi ETL',environment:'Production — Monitoring principal',type:'Base de données SQL Server',server:'BCC-SQLSERVER01',database:'DB_Monitoring_ETL',monitoringTable:'tbl_suivi_etl',status:'CONNECTED',lastCheck:'14/05/2025 07:32:15',nextCheck:'14/05/2025 07:37:15',description:'Cette source contient la table de suivi des chargements ETL avec les résultats des étapes Staging et Data Warehouse.',columns:['Date','Staging (0 = Échec, 1 = Réussi)','DW (0 = Échec, 1 = Réussi)'],rows:[['14/05/2025',1,1],['13/05/2025',1,0],['12/05/2025',1,1],['11/05/2025',0,0],['10/05/2025',1,1]],technical:{driver:'SQL Server Native Client 11.0',encoding:'UTF-8',timezone:'(UTC+01:00) Bruxelles, Kinshasa',frequency:'Toutes les 5 minutes'}},
 {id:'demo-staging-control',name:'Contrôle Staging ETL',environment:'Recette — Zone Staging',type:'Base de données SQL Server',server:'BCC-SQLSERVER-REC',database:'DB_Staging_Control',monitoringTable:'dbo.etl_execution_log',status:'CONNECTED',lastCheck:'14/05/2025 07:30:00',nextCheck:'14/05/2025 07:40:00',description:'Environnement de démonstration utilisé pour contrôler les intégrations dans la zone Staging avant validation.',columns:['DateExecution','Staging (0 = Échec, 1 = Réussi)','DW (0 = Échec, 1 = Réussi)'],rows:[['14/05/2025',1,0],['13/05/2025',1,1],['12/05/2025',1,0],['11/05/2025',1,1],['10/05/2025',1,1]],technical:{driver:'Microsoft ODBC Driver 18',encoding:'UTF-8',timezone:'(UTC+01:00) Bruxelles, Kinshasa',frequency:'Toutes les 10 minutes'}},
 {id:'demo-warehouse-reporting',name:'Entrepôt décisionnel',environment:'Démonstration — Data Warehouse',type:'Entrepôt SQL Server',server:'BCC-DW-DEMO01',database:'DW_BCC_Demo',monitoringTable:'audit.fact_load_status',status:'DISCONNECTED',lastCheck:'14/05/2025 07:25:42',nextCheck:'En attente de reconnexion',description:'Entrepôt de démonstration présentant les statuts de chargement des données consolidées destinées au reporting.',columns:['LoadDate','Staging (0 = Échec, 1 = Réussi)','DW (0 = Échec, 1 = Réussi)'],rows:[['14/05/2025',1,0],['13/05/2025',1,1],['12/05/2025',0,0],['11/05/2025',1,1],['10/05/2025',1,0]],technical:{driver:'Microsoft ODBC Driver 18',encoding:'UTF-8',timezone:'(UTC+01:00) Bruxelles, Kinshasa',frequency:'Toutes les 15 minutes'}}
];

export default function SourcePage({onNavigate}){
 const[sourceId,setSourceId]=useState(DEMO_SOURCES[0].id),[testing,setTesting]=useState(false),[message,setMessage]=useState(''),[dateOpen,setDateOpen]=useState(false),[date,setDate]=useState('2025-05-14');
 const source=useMemo(()=>DEMO_SOURCES.find(item=>item.id===sourceId)??DEMO_SOURCES[0],[sourceId]);
 const stats=useMemo(()=>{const total=source.rows.length,staging=source.rows.filter(r=>r[1]).length,dw=source.rows.filter(r=>r[2]).length;return[[FileText,'Total d’enregistrements',String(total),'document'],[CalendarDays,'Période couverte',`${total} jours`,'calendar'],[Check,'Taux de réussite Staging',`${(staging/total*100).toFixed(1).replace('.',',')} %`,'success'],[Landmark,'Taux de réussite DW',`${(dw/total*100).toFixed(1).replace('.',',')} %`,'warehouse']]},[source]);
 const dateLabel=new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'long',year:'numeric'}).format(new Date(`${date}T12:00:00`));
 const selectSource=e=>{const id=e.target.value,next=DEMO_SOURCES.find(item=>item.id===id);setSourceId(id);setMessage(`${next.name} est maintenant la source active`);window.setTimeout(()=>setMessage(''),2200)};
 const test=()=>{setTesting(true);setMessage('');window.setTimeout(()=>{setTesting(false);setMessage(source.status==='CONNECTED'?`Connexion à ${source.name} réussie`:`${source.name} est actuellement indisponible`)},700)};
 return <div className="source-page"><header className="source-page-heading"><div><h1>Source</h1><p>Informations sur la source de données surveillée</p></div><div className="source-heading-actions">
  <label className="source-selector"><Server/><span><small>Connexion surveillée</small><select aria-label="Connexion ou environnement surveillé" value={sourceId} onChange={selectSource}>{DEMO_SOURCES.map(item=><option value={item.id} key={item.id}>{item.environment}</option>)}</select></span><ChevronDown/></label>
  <div className="source-date-control"><button className={dateOpen?'active':''} aria-expanded={dateOpen} onClick={()=>setDateOpen(!dateOpen)}><CalendarDays/><span><small>Date observée</small><b>{dateLabel}</b></span><ChevronDown className={dateOpen?'open':''}/></button>{dateOpen&&<div className="source-date-pop"><header><CalendarDays/><div><b>Date des données</b><small>Sélectionnez une journée</small></div></header><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><footer><button onClick={()=>setDateOpen(false)}>Appliquer</button></footer></div>}</div>
  <div className="source-page-logo"><img src={bccLogo} alt="Banque Centrale du Congo"/><b>BANQUE CENTRALE<br/>DU CONGO</b></div>
 </div></header>{message&&<div className={`source-toast ${source.status==='DISCONNECTED'?'warning':''}`} role="status"><CheckCircle2/>{message}</div>}<div className="source-layout">
 <section className="source-card source-main"><h2>Informations de la source</h2><div className="source-main-grid"><span className="source-db"><Database/></span><dl><dt>Nom de la source</dt><dd><strong>{source.name}</strong></dd><dt>Type</dt><dd>{source.type}</dd><dt>Serveur</dt><dd>{source.server}</dd><dt>Base de données</dt><dd>{source.database}</dd></dl><div className="source-status"><b>Statut de connexion</b><p className={source.status==='CONNECTED'?'connected':'disconnected'}><i/>{source.status==='CONNECTED'?'Connectée':'Déconnectée'}</p><hr/><b>Dernière vérification</b><p><Clock3/>{source.lastCheck}</p><hr/><b>Prochaine vérification</b><p><Clock3/>{source.nextCheck}</p></div></div></section>
 <section className="source-card source-description"><h2>Description</h2><div className="description-intro"><span><Database/></span><p>{source.description}</p></div><b>Table surveillée</b><p>{source.monitoringTable}</p><b>Colonnes surveillées</b><ul>{source.columns.map(c=><li key={c}>{c}</li>)}</ul></section>
 <section className="source-card source-preview"><h2>Aperçu des données de la source</h2><table><thead><tr><th>Date <ChevronsUpDown/></th><th>Staging <ChevronsUpDown/></th><th>DW <ChevronsUpDown/></th></tr></thead><tbody>{source.rows.map(r=><tr key={r[0]}><td><b>{r[0]}</b></td><td><span className={r[1]?'one':'zero'}>{r[1]}</span></td><td><span className={r[2]?'one':'zero'}>{r[2]}</span></td></tr>)}</tbody></table><button onClick={()=>onNavigate('Historique')}>Voir plus d’historique <ArrowRight/></button></section>
 <section className="source-card source-statistics"><h2>Statistiques de la source</h2><div>{stats.map(([Icon,label,value,tone])=><article key={label}><span className={tone}><Icon/></span><p>{label}<strong>{value}</strong></p></article>)}</div></section>
 <section className="source-card source-technical"><h2>Informations techniques</h2><dl><div><dt>Driver</dt><dd>{source.technical.driver}</dd></div><div><dt>Encodage</dt><dd>{source.technical.encoding}</dd></div><div><dt>Fuseau horaire</dt><dd>{source.technical.timezone}</dd></div><div><dt>Fréquence de lecture</dt><dd>{source.technical.frequency}</dd></div></dl><button onClick={test} disabled={testing}><RefreshCw className={testing?'spin':''}/>{testing?'Test en cours…':'Tester la connexion'}</button></section>
 </div></div>
}
